# i3blocks config file
#
# Please see man i3blocks for a complete reference!
# The man page is also hosted at http://vivien.github.io/i3blocks
#
# List of valid properties:
#
# align
# color
# command
# full_text
# instance
# interval
# label
# min_width
# name
# separator
# separator_block_width
# short_text
# signal
# urgent

# Global properties
#
# The top properties below are applied to every block, but can be overridden.
# Each block command defaults to the script name to avoid boilerplate.
# Change $SCRIPT_DIR to the location of your scripts!
command=$HOME/.config/i3/scripts/$BLOCK_NAME
# full_text=
separator_block_width=7
markup=none
#color=#DCDCDC
separator=false

#[apt-upgrades]
#command=$HOME/.config/i3/scripts/apt-upgrades
#signal=1
#interval=3600
#PENDING_SYMBOL="\uf021 "
#SYMBOL_ONLY=0
#ALWAYS_PRINT=1
#PENDING_COLOR="#0f9355"
#NONPENDING_COLOR="#dcdcdc"
#separator=false

#[ping]
#command=ping -c 1 ping.sunet.se | tail -1| awk '{print $4}' | cut -d '/' -f 2 | sed 's/\..*$/ ms/g'
#label=  
#interval=5
#separator=false

# Network interface and VPN monitoring
#
# If the instance is not specified, use the interface used for default route.
# The address can be forced to IPv4 or IPv6 with -4 or -6 switches.
# Support multiple VPN, with colors.
#[ping]
#command=/home/faust/.config/i3/scripts/ping
#label=
#interval=5
#separator=false

#[memory]
#command=$HOME/.config/i3/scripts/memory
#label=
#interval=30
#separator=false

#[disk]
#command=$HOME/.config/i3/scripts/disk -f " {pused}%" -tc '{pfree}' '<' 20 -tc '{pfree}' '<' 10
#instance=/home
#interval=3600

#[temperature]
#command=$HOME/.config/i3/scripts/temperature
#label=
#interval=5
#T_WARN=60
#T_CRIT=90
#SENSOR_CHIP=""

#[volume]
#command=$HOME/.config/i3/scripts/volume -f "{icon} {volume}%" -id "" -im "" -fe '{port}' '=' 'headphone' '{icon}  {volume}%' -fe '{dev_bus}' '=' 'bluetooth' '{icon}  {volume}%' -tw '{muted}' '=' 'yes'
#markup=pango
#interval=1

#separator=false

#[battery-plus]
#command=$HOME/.config/i3/scripts/battery-plus
#markup=pango
#instance=BAT0
#interval=30
#_FONT=FontAwesome
#_PERCENT=&#x25;
#_HIDE_IF_CHARGED=false
#_USE_BATT_GRADIENT=false
#_SYMBOLS_ONLY=false
#_HIDE_PERCENTAGE=false
#_HIDE_TIME_REMAINING=true
#_HIDE_TIME_TO_FULL=true
#_SHOW_CHARGE_DIRECTION=true
#_CAPACITY_ALERT=75
#_CRITICAL_ACTION=notify
#_LOW_ACTION=notify
#_NOTIFY_PROGRAM=notify-send
#_NOTIFY_EXPIRES=1500
#_NOTIFY_THROTTLE=120
#_COLOR_FULLY_CHARGED=
#_COLOR_CHARGING=#f69856
#_COLOR_DISCHARGING=#f69856
#_COLOR_PENDING=#145eb8
#_COLOR_ERROR=#f0544c
#_COLOR_BATTERY=#dcdcdc
#_COLOR_ALERT=#e47c26
#_COLOR_DIRECTIONAL_UP=#0f9355
#_COLOR_DIRECTIONAL_DOWN=#f0544c
#_COLOR_GRADIENT_START=#00FF00
#_COLOR_GRADIENT_END=#f0544c
#_SYMBOL_FULLY_CHARGED=
#_SYMBOL_CHARGING=&#xf0e7;
#_SYMBOL_DISCHARGING=
#_SYMBOL_UNKNOWN=&#xf128;
#_SYMBOL_PENDING=&#xf254;
#_SYMBOL_ERROR=&#xf00d;
#_SYMBOL_ALERT=&#xf071;
#_SYMBOL_BATT_100=&#xf240;
#_SYMBOL_BATT_75=&#xf241;
#_SYMBOL_BATT_50=&#xf242;
#_SYMBOL_BATT_25=&#xf243;
#_SYMBOL_BATT_0=&#xf244;
#_SYMBOL_DIRECTION_UP=&#8593;
#_SYMBOL_DIRECTION_DOWN=&#8595;
#separator=false

[layout]
command=$HOME/.config/i3/scripts/layout
#interval=persist

[time]
command= date '+%H:%M'
interval=5
label= 
color=#dcdcdc

#[rofi-calendar]
#command=$HOME/.config/i3/scripts/rofi-calendar
#interval=5
#LABEL=
#DATEFTM=+%a. %d. %b. %Y
#SHORTFTM=+%d.%m.%Y

#[dunst]
#command=$HOME/.config/i3/scripts/dunst
#interval=once
#format=json
#markup=pango
#min_width=50
#align=center
#DUNST_MUTE=off

[separator]
separator_block_width=1
full_text=
