default_linemode devicons
set preview_images true
set preview_images_method kitty

default_linemode devicons

# Відправка виділеного в кошик через DD
map DD shell trash-put %s

# Швидкий перегляд кошика
map gT cd ~/.local/share/Trash/files
